title: "0xWelsh's Writeups" 
description: "A collection of my CTF writeups, security research, and notes." 
theme: jekyll-theme-cayman 


author:
  name: "0xWelsh"
  url: "https://github.com/0xWelsh" 


collections:
  writeups:
    output: true
    permalink: /:collection/:name
